### ISSUE TITLE
Problems with anchors

### ISSUE THREAD

**Issue by wkjesus** [Hypercubed/angular-marked#43] opened 2015-12-14 19:36 UTC
i have an issue when using anchor with directive du-smooth-scroll like this on the mark down 

* <a href='' du-smooth-scroll="app-generator"> App Generator </a>

i fix it adding $compile on the directive in this line

.directive('marked', ['marked', '$templateRequest','$compile', function (marked, $templateRequest,$compile) {

and on the element 
$compile(element.contents())(scope);

hope this change merge on future version. Greetings

**Comment by Hypercubed** [comment] 2015-12-15 05:02
Adding `$compile` (which has been suggested a few times) causes trouble with code blocks.  If you can explain further what the issue is with anchor perhaps we can come up with another solution.

**Comment by Hypercubed** [comment] 2015-12-18 04:52
@wkjesus Unfortunately your solution, as is, will not work.  As mentioned it causes code in code blocks to break.  See ['should not digest code blocks'](https://github.com/Hypercubed/angular-marked/blob/master/test/angular-marked.js#L129).  If you can get the ['should digest non-code blocks'](https://github.com/Hypercubed/angular-marked/blob/master/test/angular-marked.js#L136) test to pass without impacting other tests I'll consider that a solution.

Closing for now.  Thank you.

**Closed by Hypercubed** 2015-12-18 04:52 UTC
